service: newsbay-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  # profile: serverless-Divyanshu
  stage: dev
  environment: 
    TableName: ${self:custom.tableName}
    BucketName: ${self:custom.bucketName}
    # user_pool_id: { Ref: UserPool }
    # client_id: { Ref: UserClient }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        # - cognito-idp:*
      Resource: '*'

plugins:
  # - serverless-webpack

package:
  individually: true

custom:
  tableName: newsbay-table
  bucketName: news-bay-bucket
  webpack:
    packagerOptions:
      scripts:
        - npm install --arch=x64 --platform=linux sharp

functions:
  authenticate:
    handler: lambdas/authenticate.handler
  getCategory:
    handler: lambdas/getCategory.handler
    events:
      - http: 
          path: api/v2/category
          method: GET
          cors: true
  category:
    handler: lambdas/category.handler
    events:
      - http: 
          path: api/v2/category
          method: POST
          cors: true
          authorizer: authenticate
      - http: 
          path: api/v2/category/{category}
          method: DELETE
          cors: true
          authorizer: authenticate
  articles:
    handler: lambdas/articles.handler
    events:
      - http: 
          path: api/v2/articles
          method: ANY
          cors: true
          authorizer: authenticate
  editorJob:
    handler: lambdas/editorJob.handler
    events:
      - http:
          path: api/v2/getUnpublishedPosts
          method: GET
          cors: true
          authorizer: authenticate
      - http:
          path: api/v2/postStatus
          method: PATCH
          cors: true
          authorizer: authenticate
      - http:
          path: api/v2/deletePost
          method: DELETE
          cors: true
          authorizer: authenticate
  getArticles:
    handler: lambdas/getArticles.handler
    events:
      - http:
          path: api/v2/getArticles
          method: GET
          cors: true

resources:
  Resources:
  # s3 Bucket
    NewsBayBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
  # DynamoDB
    NewsBayDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: user-article-index
            KeySchema:
              - AttributeName: user
                KeyType: HASH
              - AttributeName: sk
                KeyType: RANGE 
            Projection:
              ProjectionType: ALL